#! /usr/bin/env bash

cd $(dirname $0)

if [ ! -x ../build/bin/zeek-agent ]; then
    echo "no build/bin/zeek-agent, cannot update README" >&2
    exit 0 # don't fail pre-commit
fi

README=../README.md

tmp=/tmp/README.$$.tmp
trap "rm -f ${tmp}" EXIT

awk '
    BEGIN                               { p = 1 }

    /<!-- begin table of contents -->/    { print;
                                          system("cat ../README.md | ./md-to-toc");
                                          p = 0; }
    /<!-- end table of contents -->/      { p = 1; }

    /<!-- begin table reference -->/    { print;
                                          system("../build/bin/zeek-agent --autodoc | ./autodoc-to-md");
                                          p = 0; }
    /<!-- end table reference -->/      { p = 1; }

    p != 0                              { print; }
' <${README} >${tmp}

cmp -s ${README} ${tmp} || mv -f ${tmp} ${README}
