#! /usr/bin/env bash
#
# Codesigns a target executable. Certificate password must be in keychain.

echo CS-XXXXXX $@ | tee >>/tmp/cs

set -e
base=$(cd $(dirname $0) && pwd)

if [ $# != 1 ]; then
    echo "Usage: $(basename $0) <target>" >&2
    exit 1
fi

if [ -z "${MACOS_CERTIFICATE_APPLICATION_ID}" ]; then
    echo "Error: MACOS_CERTIFICATE_APPLICATION_ID not set" >&2
    exit 1
fi

if [ -z "${MACOS_APP_ID}" ]; then
    echo "Error: MACOS_APP_ID not set" >&2
    exit 1
fi

target="$1"
find "${target}"

echo "== Signing code ..."

codesign \
    --deep \
    --entitlements "${base}/entitlements.plist" \
    --force \
    --identifier "${MACOS_APP_ID}" \
    --options=runtime \
    --sign "${MACOS_CERTIFICATE_APPLICATION_ID}" \
    --strict \
    --timestamp \
    "${target}"

echo "== Validating signature ..."

codesign -dv "${target}"
codesign -d --entitlements - "${target}"
