#! /usr/bin/env bash
#
# Submits a bundle (e.g., a DMG or ZIP) for Apple notarization.

echo N-XXXXXX $@

set -e

if [ $# != 1 ]; then
    echo "Usage: $(basename $0) <bundle>" >&2
    exit 1
fi

if [ -z "${MACOS_CERTIFICATE_APPLICATION_ID}" ]; then
    echo "Error: MACOS_CERTIFICATE_APPLICATION_ID not set" >&2
    exit 1
fi

if [ -z "${MACOS_APP_ID}" ]; then
    echo "Error: MACOS_APP_ID not set" >&2
    exit 1
fi

if [ -z "${MACOS_NOTARIZATION_USER}" ]; then
    echo "Error: MACOS_NOTARIZATION_USER not set" >&2
    exit 1
fi


bundle=$1

if [ -n "${MACOS_NOTARIZATION_PASSWORD}" ]; then
    password="-p @env:MACOS_NOTARIZATION_PASSWORD"
fi

codesign -f -s "${MACOS_CERTIFICATE_APPLICATION_ID}" --timestamp ${bundle}

echo "== Uploading for notarization ..."

tmp=/tmp/$(basename $0).$$.pid
trap "rm -f ${tmp}" EXIT

xcrun altool --notarize-app --primary-bundle-id "${MACOS_APP_ID}" -u "${MACOS_NOTARIZATION_USER}" ${password} -t osx -f "${bundle}" | tee ${tmp}

uuid=$(cat ${tmp} | grep "RequestUUID" | awk '{print $3}')
if [ -z "${uuid}" ]; then
    echo "Error: No UUID returned."
    exit 1
fi

echo "== Waiting for confirmation on UUID ${uuid} ..."

for i in $(seq 1 60); do
    sleep 10
    xcrun altool --notarization-info "${uuid}" -u "${MACOS_NOTARIZATION_USER}" ${password} | tee ${tmp}
    if grep -q "Status Message:" ${tmp}; then
        break
    fi
done

grep -q "Status Message: Package Approved" ${tmp}

echo "== Stapling ..."

xcrun stapler staple ${bundle}

echo "== Verifying ..."

spctl -a -vv -t install ${bundle}
xcrun stapler validate ${bundle}
