#! /bin/sh

base=$(cd "$(dirname "$0")"; pwd)

if [ ! -f "${base}/manifest" ]; then
    echo "No manifest."
    exit 1
fi

/bin/launchctl unload /Library/LaunchDaemons/org.zeek.zeek-agent.plist

cat "${base}/manifest" | while read path; do
    rm "${path}"
done

rm -f "/Library/Application Support/ZeekAgent/uuid"

rmdir "/Library/Application Support/ZeekAgent/ZeekAgent.app/Contents/MacOS"
rmdir "/Library/Application Support/ZeekAgent/ZeekAgent.app/Contents/Resources"
rmdir "/Library/Application Support/ZeekAgent/ZeekAgent.app/Contents/_CodeSignature"
rmdir "/Library/Application Support/ZeekAgent/ZeekAgent.app/Contents"
rmdir "/Library/Application Support/ZeekAgent/ZeekAgent.app"
rmdir "/Library/Application Support/ZeekAgent"
