#! /usr/bin/env bash

base=$(cd $(dirname $0) && pwd)

# Get us "modern" regexps with sed.
if [ `uname` == "Linux" ]; then
   sed="sed -r"
else
   sed="sed -E"
fi

${base}/diff-remove-timestamps |
   sed 's/H[a-zA-Z0-9]\{20,22\}\([^a-zA-Z0-9]\)/<uuid>\1/g'
