#! /bin/sh
#
# BTest helper for getting values for Zeek-related environment variables.

base=$(dirname $0)
zeek_dist=$(cat ${base}/../../build/CMakeCache.txt 2>/dev/null | grep ZEEK_DIST | cut -d = -f 2)

if [ -n "${zeek_dist}" ]; then
    if [ "$1" = "zeekpath" ]; then
        ${zeek_dist}/build/zeek-path-dev
    else
        echo "usage: $(basename $0) <var>" >&2
        exit 1
    fi
else
    # Use Zeek installation for testing. In this case zeek-config must be in PATH.
    if ! which zeek-config >/dev/null 2>&1; then
        # We don't treat this as an error because we want to run tests without Zeek too.
        exit 0
    fi

    if [ "$1" = "zeekpath" ]; then
        echo "$(cd ${base}/.. && pwd):$(zeek-config --zeekpath)"
    else
        echo "usage: $(basename $0) <var>" >&2
        exit 1
    fi
fi
